### ISSUE TITLE
maskElement cannot be animated on Android

### ISSUE THREAD

**Issue by wcandillon** [react-native-community/react-native-masked-view#22]
In `MaskedElementIOS`, `maskElement` can be nicely animated, however it doesn't seem to work on Android with this component.

**Comment by wcandillon** [comment]
This is the kind of example that would be supported if the `maskElement` can be animated on Android the same way to works on iOS: https://www.youtube.com/watch?v=gLopy2MCAqM. Source code: https://github.com/wcandillon/can-it-be-done-in-react-native/tree/master/season3/src/LiquidSwipe

**Comment by boona11** [comment]
I have same issue, any updates?

**Comment by boona11** [comment]
It tool me two days trying to figure out the issue with android and my conclusion is that the bitmap which drawn by native code is apply the mask perfectly, however it is not animatable 
![Screenshot_20191020-092504_RNwithoutExpo](https://user-images.githubusercontent.com/12968525/67155679-6de70000-f31c-11e9-98e8-7f11102eafc7.jpg)

**Comment by Axenu** [comment]
Has there been any progress on solving this? 

I can't display an image inside the mask view with another image as the maskElement.

`<MaskedView
        maskElement={(
          <Image
            source={require('../assets/image_mask.png')}
          />
              )}
      >
        <image
          source={image}
        />
      </MaskedView>`

It does not render anything. If I set a backgroundcolor on maskelement it render the image (expected). 

Reloading the code using fast reload render the image until the next reread of the view.
Unfortunately I know too little about android development to attempt solving this myself

**Comment by wcandillon** [comment]
I have another use case for an animated maskElement that doesn't work on Android, let me know if this is helpful to provide it. 

Right now, the best workaround to this is to use `ClipPath` from RN SVG but this has serious limitations.

**Comment by crutchcorn** [comment]
I'm in need of this functionality as well for Android

**Comment by JustinFemh** [comment]
@wcandillon I think the recently [merged pull request](https://github.com/react-native-community/react-native-masked-view/commit/5e295c01125e22fad973cb4e63a21b28129b27a1) fixed the visualization issue in your tutorial. But the performance is not so good, I tried on Android devices and the FPS is so low.

**Comment by crutchcorn** [comment]
#52 seems to have resolved this issue for me in a performant manor.

**Comment by jarthursantos** [comment]
Limit the draw circle it's possible ? the current solution renders so much more than necessary

**Comment by AlexandrePalo** [comment]
If anyone has a workaround for this 👍

**Comment by wcandillon** [comment]
As @JustinFemh mentioned this seems to be have been fixed. @heroic what did you think about the performance?

**Comment by crutchcorn** [comment]
@wcandillon for my usage, the performance has been impeccable. You can see in the package I've built that the animations are fluid, even with a somewhat complex animation: 

https://github.com/crutchcorn/react-native-button-toggle-group

**Comment by wcandillon** [comment]
Thks @crutchcorn !

**Comment by FonDorn** [comment]
@wcandillon if there were some performance issues we will work on it. Waiting for a new episode from you ;)

**Comment by Alb93** [comment]
Hi @wcandillon, still not able to make your liquid-swipe example working with the latest react-native-masked-view version. Any suggestion?

**Comment by heroic** [comment]
@wcandillon none noticeable!

**Comment by Stevemoretz** [comment]
Damn this is really slow though it works!

**Comment by wcandillon** [comment]
hehe indeed, it's because on every frame, it takes a snapshot of the view and then applies the mask. It's all done on the CPU. I'm not sure what is the best practice on Android for such use case.

**Comment by hannojg** [comment]
I don't get it. MaskedElement is still not animate-able on android using the latest version of this library on android. Is it just me or everyone else too?

**Comment by hannojg** [comment]
I see that this PR tries to add the animation support back by giving us the opportunity to set the rendering mode to software manually. However, even when doing this, I can't run animations on the MaskElement on android

**Comment by carlos3g** [comment]
animatable element in `maskedElement` not working here.

**Comment by lucy-tran** [comment]
Animated maskElement still doesn't work on Android here. Any updates or suggestions on a workaround?

**Comment by MustafaZayed** [comment]
# Hardware Accelerated MaskView Animations in React Native Android
This is a workaround for the performance issues with MaskView animations on Android devices in React Native. While the MaskView animations work well on iOS, they pose some performance issues on Android.

### The Issue:

When androidRenderingMode is set to `software`, the animations work but the performance is poor with barely 10 fps. However, with androidRenderingMode set to `hardware`, the animations work as long as the MaskView element is in motion at initialization. Once the element stops, it freezes and cannot be animated anymore. The performance, however, is far better with 45 - 60 fps.

### The Workaround:

The workaround involves keeping the MaskView element always in motion. Trying this from the JavaScript code results in performance issues, with the framerate dropping to around 15-30 fps.

A more efficient solution is to modify the native code to keep the UI thread constantly moving the element. This results in a performance increase of up to 60 fps.

Here's the patch for the changes that you can use with [patch-package](https://www.npmjs.com/package/patch-package):

@react-native-masked-view+masked-view+0.2.9.patch
```diff
diff --git a/node_modules/@react-native-masked-view/masked-view/android/src/main/java/org/reactnative/maskedview/RNCMaskedView.java b/node_modules/@react-native-masked-view/masked-view/android/src/main/java/org/reactnative/maskedview/RNCMaskedView.java
index 4615d21..dfa80a8 100644
--- a/node_modules/@react-native-masked-view/masked-view/android/src/main/java/org/reactnative/maskedview/RNCMaskedView.java
+++ b/node_modules/@react-native-masked-view/masked-view/android/src/main/java/org/reactnative/maskedview/RNCMaskedView.java
@@ -7,6 +7,7 @@ import android.graphics.Paint;
 import android.graphics.PorterDuff;
 import android.graphics.PorterDuffXfermode;
 import android.view.View;
+import android.animation.ValueAnimator;
 
 import com.facebook.react.views.view.ReactViewGroup;
 
@@ -17,6 +18,7 @@ public class RNCMaskedView extends ReactViewGroup {
   private boolean mBitmapMaskInvalidated = false;
   private Paint mPaint;
   private PorterDuffXfermode mPorterDuffXferMode;
+  private ValueAnimator animator;
 
   public RNCMaskedView(Context context) {
     super(context);
@@ -26,6 +28,18 @@ public class RNCMaskedView extends ReactViewGroup {
 
     mPaint = new Paint(Paint.ANTI_ALIAS_FLAG);
     mPorterDuffXferMode = new PorterDuffXfermode(PorterDuff.Mode.DST_IN);
+
+    animator = ValueAnimator.ofFloat(0, 1);
+    animator.setDuration(60000); // Change duration as needed
+    animator.setRepeatCount(ValueAnimator.INFINITE);
+    animator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
+        @Override
+        public void onAnimationUpdate(ValueAnimator animation) {
+    // Force a refresh on each animation frame
+    invalidate();
+        }
+    });
+    animator.start();
   }
 
   @Override
@@ -112,4 +126,13 @@ public class RNCMaskedView extends ReactViewGroup {
       setLayerType(LAYER_TYPE_HARDWARE, null);
     }
   }
+
+  @Override
+    protected void onDetachedFromWindow() {
+        super.onDetachedFromWindow();
+        // Stop the animator when view is detached
+        if (animator != null) {
+            animator.end();
+        }
+    }
 }
```
This may not be the most elegant solution, but it works and hopefully can inspire a more efficient solution from a more experienced Android engineer.

Thanks to [@wcandillon](https://github.com/wcandillon) for the [Liquid Swipe](https://www.youtube.com/watch?v=6jxy5wfNpk0&t=2247s) example that inspired this workaround.

And here's a video showing how the Liquid Swipe example looks on my Android 10 device with `androidRenderingMode="hardware"`:

https://github.com/react-native-masked-view/masked-view/assets/7797467/d1cf2faa-4079-453a-9515-7d72511013bb

**Comment by WzDTj** [comment]
> # Hardware Accelerated MaskView Animations in React Native Android
> This is a workaround for the performance issues with MaskView animations on Android devices in React Native. While the MaskView animations work well on iOS, they pose some performance issues on Android.
> 
> ### The Issue:
> When androidRenderingMode is set to `software`, the animations work but the performance is poor with barely 10 fps. However, with androidRenderingMode set to `hardware`, the animations work as long as the MaskView element is in motion at initialization. Once the element stops, it freezes and cannot be animated anymore. The performance, however, is far better with 45 - 60 fps.
> 
> ### The Workaround:
> The workaround involves keeping the MaskView element always in motion. Trying this from the JavaScript code results in performance issues, with the framerate dropping to around 15-30 fps.
> 
> A more efficient solution is to modify the native code to keep the UI thread constantly moving the element. This results in a performance increase of up to 60 fps.
> 
> Here's the patch for the changes that you can use with [patch-package](https://www.npmjs.com/package/patch-package):
> 
> @react-native-masked-view+masked-view+0.2.9.patch
> 
> ```diff
> diff --git a/node_modules/@react-native-masked-view/masked-view/android/src/main/java/org/reactnative/maskedview/RNCMaskedView.java b/node_modules/@react-native-masked-view/masked-view/android/src/main/java/org/reactnative/maskedview/RNCMaskedView.java
> index 4615d21..dfa80a8 100644
> --- a/node_modules/@react-native-masked-view/masked-view/android/src/main/java/org/reactnative/maskedview/RNCMaskedView.java
> +++ b/node_modules/@react-native-masked-view/masked-view/android/src/main/java/org/reactnative/maskedview/RNCMaskedView.java
> @@ -7,6 +7,7 @@ import android.graphics.Paint;
>  import android.graphics.PorterDuff;
>  import android.graphics.PorterDuffXfermode;
>  import android.view.View;
> +import android.animation.ValueAnimator;
>  
>  import com.facebook.react.views.view.ReactViewGroup;
>  
> @@ -17,6 +18,7 @@ public class RNCMaskedView extends ReactViewGroup {
>    private boolean mBitmapMaskInvalidated = false;
>    private Paint mPaint;
>    private PorterDuffXfermode mPorterDuffXferMode;
> +  private ValueAnimator animator;
>  
>    public RNCMaskedView(Context context) {
>      super(context);
> @@ -26,6 +28,18 @@ public class RNCMaskedView extends ReactViewGroup {
>  
>      mPaint = new Paint(Paint.ANTI_ALIAS_FLAG);
>      mPorterDuffXferMode = new PorterDuffXfermode(PorterDuff.Mode.DST_IN);
> +
> +    animator = ValueAnimator.ofFloat(0, 1);
> +    animator.setDuration(60000); // Change duration as needed
> +    animator.setRepeatCount(ValueAnimator.INFINITE);
> +    animator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
> +        @Override
> +        public void onAnimationUpdate(ValueAnimator animation) {
> +    // Force a refresh on each animation frame
> +    invalidate();
> +        }
> +    });
> +    animator.start();
>    }
>  
>    @Override
> @@ -112,4 +126,13 @@ public class RNCMaskedView extends ReactViewGroup {
>        setLayerType(LAYER_TYPE_HARDWARE, null);
>      }
>    }
> +
> +  @Override
> +    protected void onDetachedFromWindow() {
> +        super.onDetachedFromWindow();
> +        // Stop the animator when view is detached
> +        if (animator != null) {
> +            animator.end();
> +        }
> +    }
>  }
> ```
> 
> This may not be the most elegant solution, but it works and hopefully can inspire a more efficient solution from a more experienced Android engineer.
> 
> Thanks to @wcandillon for the [Liquid Swipe](https://www.youtube.com/watch?v=6jxy5wfNpk0&t=2247s) example that inspired this workaround.
> 
> And here's a video showing how the Liquid Swipe example looks on my Android 10 device with `androidRenderingMode="hardware"`:
> 
>  2023_06_13_16_16_05_1_resized.mp4

This really works for me! 
THANKS!!!!
